class MyLeavesModel {
  String leaveTitle;
  String fromDate;
  String toDate;
  bool coveringEmployee;
  String leaveType;
  String type;
  String session;
  String description;
  String status;

  MyLeavesModel({
    required this.leaveTitle,
    required this.fromDate,
    required this.toDate,
    required this.coveringEmployee,
    required this.leaveType,
    required this.type,
    required this.session,
    required this.description,
    required this.status,
  });

  factory MyLeavesModel.fromJson(Map<String, dynamic> json) {
    bool b(dynamic v, {bool def = false}) {
      if (v == null) return def;
      if (v is bool) return v;
      final s = v.toString().toLowerCase().trim();
      if (s == 'true' || s == '1' || s == 'yes') return true;
      if (s == 'false' || s == '0' || s == 'no') return false;
      return def;
    }

    // Existing generated/legacy parsing might not match v2 API.
    // This implementation tolerates both shapes.

    // Helper to safely read values
    String s(dynamic v) => (v == null) ? '' : v.toString();

    // Ensure common legacy bool fields exist to avoid null->bool cast issues
    json['autoGenerated'] = b(json['autoGenerated'] ?? json['auto_generated']);
    json['auto_generated'] = b(json['auto_generated'] ?? json['autoGenerated']);
    json['removed'] = b(json['removed']);
    json['isHoliday'] = b(json['isHoliday'] ?? (json['slot'] is Map ? (json['slot']['isHoliday']) : null));
    json['isOffday'] = b(json['isOffday'] ?? (json['slot'] is Map ? (json['slot']['isOffday']) : null));
    json['coveringEmployee'] = b(json['coveringEmployee'] ?? json['covering_employee']);

    // v2 fields
    final String v2Type = s(json['type'] ?? json['leave_type']);
    final String v2Status = s(json['status']);
    final String v2Reason = s(json['reason'] ?? json['leave_title'] ?? json['leaveTitle'] ?? json['description']);

    // Try to build from/to dates
    String pickDate(dynamic v) {
      if (v == null) return '';
      // already formatted
      final str = v.toString();
      if (str.contains('/') || str.contains('-')) return str;
      // epoch seconds
      final sec = int.tryParse(str);
      if (sec == null) return str;
      final dt = DateTime.fromMillisecondsSinceEpoch(sec * 1000);
      final dd = dt.day.toString().padLeft(2, '0');
      final mm = dt.month.toString().padLeft(2, '0');
      final yy = dt.year.toString();
      return '$dd/$mm/$yy';
    }

    String from = pickDate(json['fromDate'] ?? json['from_date']);
    String to = pickDate(json['toDate'] ?? json['to_date']);

    // If still missing, try v2 dates[]
    try {
      final dates = json['dates'];
      if ((from.isEmpty || to.isEmpty) && dates is List && dates.isNotEmpty) {
        final secs = <int>[];
        for (final d in dates) {
          final sec = (d is int) ? d : int.tryParse(d.toString());
          if (sec != null) secs.add(sec);
        }
        if (secs.isNotEmpty) {
          secs.sort();
          from = from.isNotEmpty ? from : pickDate(secs.first);
          to = to.isNotEmpty ? to : pickDate(secs.last);
        }
      }
    } catch (_) {}

    // NOTE: MyLeavesModel constructor varies between app versions.
    // Build using fields that are present in this project; provide safe defaults
    // for required fields so Leave History can render.
    return MyLeavesModel(
      // Common/required fields
      leaveTitle: s(json['leaveTitle'] ?? json['leave_title']).isNotEmpty
          ? s(json['leaveTitle'] ?? json['leave_title'])
          : v2Reason,
      fromDate: from,
      toDate: to,
      leaveType: s(json['leaveType'] ?? json['leave_type']).isNotEmpty
          ? s(json['leaveType'] ?? json['leave_type'])
          : v2Type,
      status: v2Status.isNotEmpty
          ? v2Status
          : s(json['leave_status'] ?? json['leaveStatus']),

      // Additional required fields in this repo
      session: s(json['session']).isNotEmpty ? s(json['session']) : 'full_day',
      coveringEmployee: b(json['coveringEmployee'] ?? json['covering_employee']),

      // Optional fields when available
      type: v2Type,
      description: s(json['description']).isNotEmpty
          ? s(json['description'])
          : v2Reason,
    );
  }

  /// Build a MyLeavesModel from the v2 leave API shape or from a normalized map.
  /// Use this for the v2 endpoint to avoid legacy json parsing issues.
  factory MyLeavesModel.fromV2(Map<String, dynamic> json) {
    String s(dynamic v) => (v == null) ? '' : v.toString();

    // dates can be formatted strings or epoch seconds
    String fmtDate(dynamic v) {
      if (v == null) return '';
      final str = v.toString();
      if (str.contains('/') || str.contains('-')) return str;
      final sec = int.tryParse(str);
      if (sec == null) return str;
      final dt = DateTime.fromMillisecondsSinceEpoch(sec * 1000);
      final dd = dt.day.toString().padLeft(2, '0');
      final mm = dt.month.toString().padLeft(2, '0');
      final yy = dt.year.toString();
      return '$dd/$mm/$yy';
    }

    // Resolve date range
    String from = fmtDate(json['fromDate'] ?? json['from_date']);
    String to = fmtDate(json['toDate'] ?? json['to_date']);
    try {
      final dates = json['dates'];
      if ((from.isEmpty || to.isEmpty) && dates is List && dates.isNotEmpty) {
        final secs = <int>[];
        for (final d in dates) {
          final sec = (d is int) ? d : int.tryParse(d.toString());
          if (sec != null) secs.add(sec);
        }
        if (secs.isNotEmpty) {
          secs.sort();
          if (from.isEmpty) from = fmtDate(secs.first);
          if (to.isEmpty) to = fmtDate(secs.last);
        }
      }
    } catch (_) {}

    // Common text fields
    final type = s(json['leave_type'] ?? json['type']);
    final status = s(json['status'] ?? json['leave_status']);
    final title = s(json['leave_title'] ?? json['leaveTitle'] ?? json['reason'] ?? json['description']);

    // Some constructors require these in this repo
    final session = s(json['session']).isNotEmpty ? s(json['session']) : 'full_day';
    final coveringEmployee = (json['coveringEmployee'] ?? json['covering_employee'] ?? false) == true;

    // Optional fields when available
    return MyLeavesModel(
      leaveTitle: title,
      fromDate: from,
      toDate: to,
      leaveType: type,
      status: status,
      session: session,
      coveringEmployee: coveringEmployee,
      type: type,
      description: s(json['description']).isNotEmpty ? s(json['description']) : title,
    );
  }
}
