import 'dart:convert';
import 'package:cn_pocket_hr/api/api_client.dart';
import 'package:cn_pocket_hr/config/flavor_config.dart';
import 'package:cn_pocket_hr/models/hr/leave_model.dart';
import 'package:flutter/foundation.dart';

class LeaveService {
  static Future<List<MyLeavesModel>> getMyLeaves() async {
    try {
      final uid = await ApiClient.getResolvedUserId();
      if (uid == null || uid.isEmpty) throw Exception('Missing user id');

      final url = '${FlavorConfig.instance.apiBaseUrl}/leave';
      final res = await ApiClient.get(url,
          queryParams: {'userIds': uid, 'mobile': 'true'});

      if (res.statusCode < 200 || res.statusCode >= 300) return [];

      final decoded = jsonDecode(res.body);
      if (decoded is! Map) return [];

      final map = Map<String, dynamic>.from(decoded);
      if (map['success'] != true) return [];

      final dataAny = map['data'];
      if (dataAny is! List) return [];

      final out = <MyLeavesModel>[];
      for (final item in dataAny) {
        if (item is! Map) continue;
        final it = Map<String, dynamic>.from(item);

        final dateSecs = <int>[];
        try {
          final dates = it['dates'];
          if (dates is List) {
            for (final d in dates) {
              final sec = (d is int) ? d : int.tryParse(d.toString());
              if (sec != null) dateSecs.add(sec);
            }
          }
        } catch (_) {}

        int? fromSec;
        int? toSec;
        if (dateSecs.isNotEmpty) {
          dateSecs.sort();
          fromSec = dateSecs.first;
          toSec = dateSecs.last;
        }

        String? fmtDdMmYyyy(int? sec) {
          if (sec == null) return null;
          try {
            final dt = DateTime.fromMillisecondsSinceEpoch(sec * 1000);
            return '${dt.day.toString().padLeft(2, '0')}/${dt.month.toString().padLeft(2, '0')}/${dt.year}';
          } catch (_) {
            return null;
          }
        }

        final fromStr = fmtDdMmYyyy(fromSec);
        final toStr = fmtDdMmYyyy(toSec);

        final reason =
            (it['reason'] ?? it['title'] ?? it['leave_title'] ?? '').toString();
        final type = (it['type'] ?? '').toString();
        final status = (it['status'] ?? '').toString();

        final normalized = <String, dynamic>{
          '_id': (it['_id'] ?? it['id'] ?? '').toString(),
          'id': (it['_id'] ?? it['id'] ?? '').toString(),
          'status': status,
          'type': type,
          'leave_type': type,
          'leaveTitle': reason,
          'leave_title': reason,
          'reason': reason,
          'description': reason,
          'fromDate': fromStr,
          'toDate': toStr,
          'from_date': fromStr,
          'to_date': toStr,
          'dates': dateSecs,
          'session': (it['session'] != null && it['session'].toString().isNotEmpty)
              ? it['session'].toString()
              : ((it['leave_type'] == 'half' || it['type'] == 'half')
                  ? (it['half_period'] ?? 'half').toString()
                  : 'full_day'),
          'autoGenerated':
              (it['autoGenerated'] ?? it['auto_generated'] ?? false) == true,
          'auto_generated':
              (it['coveringEmployee'] ?? it['covering_employee'] ?? false) ==
                  true,
          'removed': (it['removed'] ?? false) == true,
          'isHoliday': (it['isHoliday'] ??
                  (it['slot'] is Map
                      ? (it['slot']['isHoliday'] ?? false)
                      : false)) ==
              true,
          'isOffday': (it['isOffday'] ??
                  (it['slot'] is Map
                      ? (it['slot']['isOffday'] ?? false)
                      : false)) ==
              true,
          'coveringEmployee':
              (it['coveringEmployee'] ?? it['covering_employee'] ?? false) ==
                  true,
          'covering_employee':
              (it['coveringEmployee'] ?? it['covering_employee'] ?? false) ==
                  true,
          'employeeName': it['employeeName'],
          'userId': it['userId'],
          'slot': it['slot'],
        };

        try {
          out.add(MyLeavesModel.fromJson(normalized));
        } catch (e) {
          debugPrint('[LEAVE SERVICE] MyLeavesModel.fromJson failed: $e');
        }
      }
      return out;
    } catch (e, st) {
      debugPrint('[LEAVE SERVICE] err: $e');
      debugPrint(st.toString());
      return [];
    }
  }
}
